import { Inter } from "next/font/google";
import "./globals.css";
import CommonLayout from "@/components/custom/CommonLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next App With Auth Js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <CommonLayout>
          {children}
        </CommonLayout>
      </body>
    </html>
  );
}
