import { Inter } from "next/font/google";
import "./globals.css";
import { AddUserContextProvider } from "@/context/userContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
        <AddUserContextProvider>
        <body className={inter.className}>
        {children}
        </body>
        </AddUserContextProvider>
    </html>
  );
}
